//
//  File.swift
//  
//
//  Created by Adrian Böhme on 20.08.24.
//

import Foundation

public struct ToolCall: Codable {
    /// The arguments to call the function with, as generated by the model in JSON format.
    ///
    /// - Note: The model does not always generate valid JSON, and may hallucinate parameters not
    /// defined by your function schema. Validate the arguments in your code before calling your function.
    public let id: String

    /// The name of the function to call.
    public let type: String
    
    public let function: FunctionCall
    
    public init(id: String, type: String, function: FunctionCall) {
        self.id = id
        self.type = type
        self.function = function
    }
    
    public var body: [String: Any] {
        return [
            "id": self.id,
            "type": self.type,
            "function": self.function.body,
        ]
    }
}
